### ISSUE TITLE
Cannot find type definition file for 'core-js' & web-animations-next.min.js

### ISSUE THREAD

**Issue by qwert789** [dominique-mueller/angular-notifier#1]
Problem when using with angular-cli:

> Module build failed: Error: C:/angular-notifier-demo/node_modules/angular-notifier/src/components/notifier-notification.component.d.ts (1,1): Cannot find type de
> finition file for 'core-js'.)

Which is this line:
` /// <reference types="core-js" /> ` gives error, please remove from follow files:
notifier-notification.component.d.ts
notifier-animation.model.d.ts
notifier-timer.service.d.ts files

Also there is **web-animations-next.min.js** dependency which is not clearly documented.

**Comment by dominique-mueller** [comment]
Hey there, thanks for opening this issue!

Should be fixed with v1.0.1 - removed the core-js typings, and also got rid of the web-animation-js peer dependency. However, browser support for Web Animations (which this library is using, as was angular2-notifier) is not really good. That's why I still highly recommend to include the polyfill, which is called **web-animations-next.min.js**.

I've updated the polyfill section in the README to be more clear on that point. Let me know if anything is unclear.
