### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by NaLLiFFuNT** [dominique-mueller/angular-notifier#16]
I've already updated my application up to Angular 4.
When i installed npm dependencies i saw the following warnings:

> npm WARN angular-notifier@1.0.4 requires a peer of @angular/core@2.x but none was installed.
npm WARN angular-notifier@1.0.4 requires a peer of @angular/common@2.x but none was installed.
npm WARN angular-notifier@1.0.4 requires a peer of rxjs@5.0.1 but none was installed.

Are you planning to keep up to date your dependencies ?

**Comment by dominique-mueller** [comment]
The latest PR, #14, addresses this issue briefly - I've extended the range of possible Angular versions. If you update **angular-notifier** from version **1.0.4** to **1.0.5**, the warnings should disappear. Can you confirm this?

I'm also planing to update the library to be fully compatible to Angular 4 so that we can use the new Angular 4 features - as soon as I find the time for it.

**Comment by NaLLiFFuNT** [comment]
I cleared node_modules, increased the package version, reinstalled all the project modules, however issue wasn't gone.
